module.exports = {
  CHAT: 'CHAT',
  USER_CONNECTED: 'USER_CONNECTED',
  MESSAGE_RECIEVED: 'MESSAGE_RECIEVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  USER_DISCONECTED: 'USER_DISCONECTED',
  TYPING: 'TYPING',
  VERIFY_USER: 'VERIFY_USER',
  LOGOUT: 'LOGOUT',
  ONLINE_USERS: 'ONLINE_USERS',
  TYPING_REC: 'TYPING_REC'
};
